#!/usr/bin/env python3
"""Track a SHA-256 per document, and list documents added, changed or removed since the plan read them.

The manifest is planning/research/docs-manifest.md. Hashes use the text with LF line
endings, so a Windows checkout with CRLF endings hashes the same as Linux.

  docs_manifest.py                 compare docs/ with the manifest (the default)
  docs_manifest.py --update        record every document as read now
  docs_manifest.py --update 04 05  record only these documents (after reading them in full)

Exit codes: 0 no changes; 1 documents added, changed or removed; 2 no manifest yet.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import configure_stdout, md_table, planning_dir, read_text, repo_root, resolve_doc, tables, today, write_text  # noqa: E402

MANIFEST = Path("research") / "docs-manifest.md"


def current(root: Path) -> Dict[str, Dict]:
    out = {}
    for p in sorted((root / "docs").glob("*.md")):
        text = read_text(p)
        out[p.name] = {"sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(), "lines": text.count("\n") + (0 if text.endswith("\n") else 1)}
    return out


def recorded(root: Path) -> Dict[str, Dict]:
    path = planning_dir(root) / MANIFEST
    if not path.exists():
        return {}
    for header, rows, _ in tables(read_text(path)):
        if header[:1] == ["Document"]:
            return {r[0].strip("`"): {"lines": r[1], "sha256": r[2].strip("`"), "recorded": r[3]} for r in rows if len(r) >= 4}
    return {}


def compare(root: Path) -> Dict[str, List[str]]:
    cur, rec = current(root), recorded(root)
    return {
        "added": sorted(set(cur) - set(rec)),
        "removed": sorted(set(rec) - set(cur)),
        "changed": sorted(n for n in set(cur) & set(rec) if cur[n]["sha256"] != rec[n]["sha256"]),
        "exists": [str(bool(rec))],
    }


def update(root: Path, only: List[str], day: str) -> List[str]:
    cur, rec = current(root), recorded(root)
    names = list(cur) if not only else []
    for o in only:
        p = resolve_doc(root, o)
        if p is None:
            raise SystemExit(f"Unknown document: {o}")
        names.append(p.name)
    for n in names:
        rec[n] = {"lines": cur[n]["lines"], "sha256": cur[n]["sha256"], "recorded": day}
    for n in [n for n in rec if n not in cur and not only]:
        del rec[n]
    rows = [[f"`{n}`", rec[n]["lines"], f"`{rec[n]['sha256']}`", rec[n]["recorded"]] for n in sorted(rec)]
    text = "\n".join([
        "# Documents manifest", "",
        "Generated by `planning/scripts/docs_manifest.py`. One row per document, recorded when the plan last read it in full.",
        "A changed hash means the plan may be out of date: `/dh` reads the changed documents and proposes plan changes.", "",
        md_table(["Document", "Lines", "SHA-256", "Recorded"], rows), ""])
    write_text(planning_dir(root) / MANIFEST, text)
    return names


def main() -> int:
    configure_stdout()
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__.split("\n\n", 1)[1])
    ap.add_argument("--update", nargs="*", metavar="DOC", help="record documents as read (all when none are named)")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--today")
    args = ap.parse_args()
    root = repo_root()
    if args.update is not None:
        names = update(root, args.update, today(args.today).isoformat())
        print(f"Recorded {len(names)} documents in planning/{MANIFEST.as_posix()}.")
        return 0
    if not recorded(root):
        print("No manifest yet: the plan hasn't recorded which documents it read. Run with --update after reading them.")
        return 2
    diff = compare(root)
    diff.pop("exists")
    if args.json:
        print(json.dumps(diff, indent=1))
    elif any(diff.values()):
        for k, v in diff.items():
            if v:
                print(f"{k.capitalize()}: {', '.join(v)}")
    else:
        print("No document changed since the plan read them.")
    return 1 if any(diff.values()) else 0


if __name__ == "__main__":
    sys.exit(main())
